"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed
four million.

From http://projecteuler.net/index.php?section=problems&id=2
"""

from eulerlib import fibonacci

def problem002(max):
    return sum([i for i in fibonacci(max) if i % 2 == 0])

if __name__ == '__main__':
    print problem002(4000000)



